Chore: Concurrent modification example (For How-to article)
dgraph-io/dgraph4j pull request #157
Opened 2020-09-10 11:28 UTC by anand-chandrashekar

This is the code base for a new how-to article on handling concurrent modifications.

2020-09-10 11:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dgraph-io/dgraph4j?pullRequest=157) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dgraph-io/dgraph4j?pullRequest=157) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dgraph-io/dgraph4j?pullRequest=157) it.</sub>

2020-09-15 07:56 UTC, abhimanyusinghgaur requested changes
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph4j/157)* status: 0 of 6 files reviewed, 13 unresolved discussions (waiting on @abhimanyusinghgaur, @anand-chandrashekar, and @danielmai)

___
*[samples/concurrent-modification/pom.xml, line 5 at r1](https://reviewable.io/reviews/dgraph-io/dgraph4j/157#-MHFYNtNAkemymovuFIG:-MHFYNtNAkemymovuFIH:bkz0e47) ([raw file](https://github.com/dgraph-io/dgraph4j/blob/f75edfda9867b1f34604a4495ed133c1b85d2d63/samples/concurrent-modification/pom.xml#L5)):*
> ```
> <groupId>com.dgraph</groupId>
> ```
io.dgraph
___
*[samples/concurrent-modification/pom.xml, line 6 at r1](https://reviewable.io/reviews/dgraph-io/dgraph4j/157#-MHFYUjlEKWPmmK9OOBk:-MHFYUjlEKWPmmK9OOBl:b-eihydj) ([raw file](https://github.com/dgraph-io/dgraph4j/blob/f75edfda9867b1f34604a4495ed133c1b85d2d63/samples/concurrent-modification/pom.xml#L6)):*
> ```
> <artifactId>conflict-runner</artifactId>
> ```
I think, we should keep the `artifactId` same as the project name OR the project name same as the `artifactId`, whichever seems best.
___
*[samples/concurrent-modification/pom.xml, line 36 at r1](https://reviewable.io/reviews/dgraph-io/dgraph4j/157#-MHFZeTZ0EV1a_ZIACdS:-MHFZeTZ0EV1a_ZIACdT:b-hew1f1) ([raw file](https://github.com/dgraph-io/dgraph4j/blob/f75edfda9867b1f34604a4495ed133c1b85d2d63/samples/concurrent-modification/pom.xml#L36)):*
> ```
> <version>20.03.0</version>
> ```
`20.03.1`
___
*[samples/concurrent-modification/README.md, line 3 at r1](https://reviewable.io/reviews/dgraph-io/dgraph4j/157#-MHFZpvvEqcxw15SyLBb:-MHFZpvvEqcxw15SyLBc:b-9mfach) ([raw file](https://github.com/dgraph-io/dgraph4j/blob/f75edfda9867b1f34604a4495ed133c1b85d2d63/samples/concurrent-modification/README.md#L3)):*
> ```
> dgraph4
> ```
dgraph4j
___
*[samples/concurrent-modification/README.md, line 10 at r1](https://reviewable.io/reviews/dgraph-io/dgraph4j/157#-MHF_CvkB8EGQGBbeQ95:-MHF_CvkB8EGQGBbeQ96:b-n3ry4o) ([raw file](https://github.com/dgraph-io/dgraph4j/blob/f75edfda9867b1f34604a4495ed133c1b85d2d63/samples/concurrent-modification/README.md#L10)):*
> ```
> folder
> ```
directory
___
*[samples/concurrent-modification/README.md, line 26 at r1](https://reviewable.io/reviews/dgraph-io/dgraph4j/157#-MHFdLqo5JX5_QKwKagE:-MHFdLqo5JX5_QKwKagF:b-1c6qf4) ([raw file](https://github.com/dgraph-io/dgraph4j/blob/f75edfda9867b1f34604a4495ed133c1b85d2d63/samples/concurrent-modification/README.md#L26)):*
> ```
> uid0xe
> ```
a space in between looks nice: `uid 0xe`
___
*[samples/concurrent-modification/README.md, line 26 at r1](https://reviewable.io/reviews/dgraph-io/dgraph4j/157#-MHFdqiE0FnxZWBnh2AV:-MHFdqiE0FnxZWBnh2AW:b-vj9hy7) ([raw file](https://github.com/dgraph-io/dgraph4j/blob/f75edfda9867b1f34604a4495ed133c1b85d2d63/samples/concurrent-modification/README.md#L26)):*
> ```
>  ,Name
> ```
space after the comma looks nice, not before.
___
*[samples/concurrent-modification/README.md, line 27 at r1](https://reviewable.io/reviews/dgraph-io/dgraph4j/157#-MHFdbRzCA5V0ad79opd:-MHFdbRzCA5V0ad79ope:bd7hnln) ([raw file](https://github.com/dgraph-io/dgraph4j/blob/f75edfda9867b1f34604a4495ed133c1b85d2d63/samples/concurrent-modification/README.md#L27)):*
> ```
> uid0xe ,Name
> ```
the spaces
___
*[samples/concurrent-modification/README.md, line 31 at r1](https://reviewable.io/reviews/dgraph-io/dgraph4j/157#-MHFe6luDAA8eIaS3s7n:-MHFe6luDAA8eIaS3s7o:bd7hnln) ([raw file](https://github.com/dgraph-io/dgraph4j/blob/f75edfda9867b1f34604a4495ed133c1b85d2d63/samples/concurrent-modification/README.md#L31)):*
> ```
> uid0xe ,Name
> ```
the spaces
___
*[samples/concurrent-modification/README.md, line 38 at r1](https://reviewable.io/reviews/dgraph-io/dgraph4j/157#-MHF_q5IAS68gVtHqjA7:-MHF_q5IAS68gVtHqjA8:b426mvy) ([raw file](https://github.com/dgraph-io/dgraph4j/blob/f75edfda9867b1f34604a4495ed133c1b85d2d63/samples/concurrent-modification/README.md#L38)):*
> ```
> ········
> ```
seems stale spaces
___
*[samples/concurrent-modification/README.md, line 50 at r1](https://reviewable.io/reviews/dgraph-io/dgraph4j/157#-MHFeVIEEe-h4hHZ9P64:-MHFeVIEEe-h4hHZ9P65:by0pgke) ([raw file](https://github.com/dgraph-io/dgraph4j/blob/f75edfda9867b1f34604a4495ed133c1b85d2d63/samples/concurrent-modification/README.md#L50)):*
> ```
> 0x8
> ```
we should keep it `0xe`, i.e. same as the one in the logs above.
___
*[samples/concurrent-modification/src/main/java/io/dgraph/example/MultiThreadedMutationLauncher.java, line 98 at r1](https://reviewable.io/reviews/dgraph-io/dgraph4j/157#-MHFkTrw898UtcGzhG6N:-MHFkTrw898UtcGzhG6O:b7qyyo9) ([raw file](https://github.com/dgraph-io/dgraph4j/blob/f75edfda9867b1f34604a4495ed133c1b85d2d63/samples/concurrent-modification/src/main/java/io/dgraph/example/MultiThreadedMutationLauncher.java#L98)):*
> ```
> + "email: string @index(exact) .\n"
> ```
This part can be removed as it is not being used.
___
*[samples/concurrent-modification/src/main/java/io/dgraph/example/Person.java, line 6 at r1](https://reviewable.io/reviews/dgraph-io/dgraph4j/157#-MHFiVN5AHnsXYB884Kz:-MHFiVN61EwCfQ_BBglA:b9ylgwt) ([raw file](https://github.com/dgraph-io/dgraph4j/blob/f75edfda9867b1f34604a4495ed133c1b85d2d63/samples/concurrent-modification/src/main/java/io/dgraph/example/Person.java#L6)):*
> ```
> String email = "";
>   String externalid = "";
> ```
These are not being used, so should be removed.


<!-- Sent from Reviewable.io -->

2020-09-16 07:31 UTC, abhimanyusinghgaur approved these changes
Just one minor grammar comment, otherwise <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph4j/157#-:-MHKoaBd5cxjkdXwX_e3:bw358g2)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @anand-chandrashekar and @danielmai)

___
*[samples/concurrent-modification/README.md, line 10 at r2](https://reviewable.io/reviews/dgraph-io/dgraph4j/157#-MHKo2Uw1HjPY5heLEyH:-MHKo2Uw1HjPY5heLEyI:bs4xkek) ([raw file](https://github.com/dgraph-io/dgraph4j/blob/41684bdb7e5aafedfb8e28d48bf529978992eac4/samples/concurrent-modification/README.md#L10)):*
> ```
> can found
> ```
can be found


<!-- Sent from Reviewable.io -->

2020-09-25 14:45 UTC, danielmai approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 6 files at r1, 4 of 5 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph4j/157#-:-MI4iVSZBf7m9lfZ5ovp:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @anand-chandrashekar)



<!-- Sent from Reviewable.io -->

2020-09-25 14:47 UTC, merged